### ISSUE TITLE
global logger

### ISSUE THREAD

**Issue by mhubii** [ros-controls/kinematics_interface#23]
global logger leads to re-definitions for downstream users, this appears to be fixed on `master` (https://github.com/ros-controls/kinematics_interface/commit/b7958c3c0de6fbe3134d46d7393505cba02c08ff), but is a problem on `humble` source and binaries

https://github.com/ros-controls/kinematics_interface/blob/8d1c5cb44e569980e7790ed1fa3bb2ee1b25daad/kinematics_interface/include/kinematics_interface/kinematics_interface.hpp#L33

**Comment by christophfroehlich** [comment]
seems to be fixed with #21?
