### ISSUE TITLE
admittance_controller cant find kinematics_interface plugin

### ISSUE THREAD

**Issue by ViHin13** [ros-controls/kinematics_interface#77]
When i start the admittance controller from ros2_controllers package, i get these error message:

> 'According to the loaded plugin descriptions the class kinematics_interface_kdl/KinematicsInterfaceKDL with base class type kinematics_interface::KinematicsInterface does not exist. Declared types are '

if i build the kinematics_interface package with the following entry in the /kinematics_interface_kdl/package.xml

```
<export>
  <build_type>ament_cmake</build_type>
  <kinematics_interface plugin="${prefix}/kinematics_interface_kdl.xml"/>
</export>
```

everything works fine.

Do someone now, what iam doing wrong?

**Comment by christophfroehlich** [comment]
Have you built the whole stack from source? On which ROS distro?

**Comment by ViHin13** [comment]
Iam on Ubuntu 22.04 and installed the ros-humble-desktop package.

**Comment by christophfroehlich** [comment]
Have you installed all dependencies, i.e., ros-humble-kinematics-interface-kdl? (`ros2 pkg xml kinematics_interface_kdl -t version`?)

After you have compiled this repo with the change in the package.xml, it worked?

**Comment by ViHin13** [comment]
Hey Christoph,
it was the missing dependency (ros-humble-kinematics-interface-kdl), as you mentioned.
Thank you so much!
